// <auto-generated />
namespace AspMemberShip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AspNetMemberShipTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AspNetMemberShipTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201406230935212_AspNetMemberShipTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
